"""Add building_type to Cell model

Revision ID: 121da02f0be5
Revises: 
Create Date: 2025-03-05 14:51:10.200984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121da02f0be5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('CAPTURE_CELL', 'BUILD', 'UPGRADE', 'TRANSFER_RESOURCES', name='actiontype'), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('target_x', sa.Integer(), nullable=True),
    sa.Column('target_y', sa.Integer(), nullable=True),
    sa.Column('building_type', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cell', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cell', schema=None) as batch_op:
        batch_op.drop_column('building_type')

    op.drop_table('user_action')
    # ### end Alembic commands ###
