"""Add neutral_defenders field to Cell model

Revision ID: 42c498ab07ba
Revises: f7ae8ce026f2
Create Date: 2025-03-06 12:25:42.709784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c498ab07ba'
down_revision = 'f7ae8ce026f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cell', schema=None) as batch_op:
        batch_op.add_column(sa.Column('neutral_defenders', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cell', schema=None) as batch_op:
        batch_op.drop_column('neutral_defenders')

    # ### end Alembic commands ###
