"""Create user_actions table

Revision ID: f7ae8ce026f2
Revises: 121da02f0be5
Create Date: 2025-03-05 15:53:27.435310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ae8ce026f2'
down_revision = '121da02f0be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('target_x', sa.Integer(), nullable=True),
    sa.Column('target_y', sa.Integer(), nullable=True),
    sa.Column('building_type', sa.String(length=50), nullable=True),
    sa.Column('warriors', sa.Integer(), nullable=True),
    sa.Column('resources', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_action')
    op.drop_table('voting_result')
    op.drop_table('vote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('faction_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=18), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('voting_result_id', sa.INTEGER(), nullable=True),
    sa.Column('vote_type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('target_x', sa.INTEGER(), nullable=True),
    sa.Column('target_y', sa.INTEGER(), nullable=True),
    sa.Column('building_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('target_faction_id', sa.INTEGER(), nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.id'], ),
    sa.ForeignKeyConstraint(['target_faction_id'], ['faction.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['voting_result_id'], ['voting_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voting_result',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('faction_id', sa.INTEGER(), nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=18), nullable=False),
    sa.Column('target_x', sa.INTEGER(), nullable=True),
    sa.Column('target_y', sa.INTEGER(), nullable=True),
    sa.Column('building_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('target_faction_id', sa.INTEGER(), nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.Column('votes_for', sa.INTEGER(), nullable=True),
    sa.Column('votes_against', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_executed', sa.BOOLEAN(), nullable=True),
    sa.Column('execution_error', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.id'], ),
    sa.ForeignKeyConstraint(['target_faction_id'], ['faction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_action',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=18), nullable=False),
    sa.Column('turn', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('target_x', sa.INTEGER(), nullable=True),
    sa.Column('target_y', sa.INTEGER(), nullable=True),
    sa.Column('building_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_actions')
    # ### end Alembic commands ###
